app:
  config:
    id: "default-app"

llm:
  provider: ollama
  config:
    model: "qwen2.5:7b"
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false

vectordb:
  provider: chroma
  config:
    collection_name: "rest-api-app"
    dir: db
    allow_reset: true

embedder:
  provider: ollama
  config:
    model: 'bge-m3:latest'